sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="ddclient"
script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  - travis_wait ./build.sh $ADDON
